# Generated by Django 5.1.7 on 2025-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_product_added_by_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='store/'),
        ),
    ]
