# Generated by Django 5.2 on 2025-07-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('snacks', 'Snacks'), ('drinks', 'Drinks')], default='fruits', max_length=50),
        ),
    ]
